FROM nginx:alpine AS base
EXPOSE 80

FROM node:16-alpine as build
ENV NODE_ENV production
WORKDIR /build
COPY ["package.json", "."]
RUN npm install --production
COPY ["src", "src"]
COPY ["public", "public"]
RUN npm run build

FROM base AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /build/build .

