#FROM node:12.18.1
FROM node:16-alpine
ENV NODE_ENV=production
ENV WEB_SERVER_PORT=80
EXPOSE 80
WORKDIR /app
COPY ["package.json", "."]
RUN npm install --production
COPY ["src", "."]
CMD [ "node", "server.js" ]